### ISSUE TITLE
Towny taxes

### ISSUE THREAD

**Issue by luc1969** [BacoNetworks-Public-Projects/BacoIssueTracker#1]
When claiming new chunks and when the taxes are supposed to be collected the money in the town bank does not go down.

**Comment by MrHDR** [comment]
Issue fixed in 2.9.3

**Comment by MrHDR** [comment]
Edit: Still does not take upkeep or taxes

**Comment by MrHDR** [comment]
Updated part of the code used for taxes in Towny, this issue should now be fixed.
